### ISSUE TITLE
The number of recovered cases shows 0 for US

### ISSUE THREAD

**Issue by GunjanDhanuka** [swapnalshahil/project-corona#1]
![Screenshot from 2021-01-10 14-57-56](https://user-images.githubusercontent.com/68523530/104119280-4f6f8900-5354-11eb-8ce3-a1070bb65978.png)
The total number of infected and deaths is fine but there is some issue with the recovered cases part.

**Comment by swapnalshahil** [comment]
Actually, API which I used does not give data of US (recovered) now. Earlier it was showing. Thanks for informing!

**Comment by GunjanDhanuka** [comment]
Okay got it! Actually I too was working on a similar project and that is why I was taking some inspiration from your repo. Thanks. I am closing the issue then.
